# Generated by Django 3.0.8 on 2021-06-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastNmae', models.CharField(max_length=50)),
                ('MobileNumber', models.IntegerField(max_length=10, unique=True)),
                ('CountryCode', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Nationality', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('MartialStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50)),
                ('NumberOfDependents', models.IntegerField()),
                ('YearsOfExpereince', models.IntegerField()),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVprofileSubmission.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVprofileSubmission.User'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeTitle', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=100)),
                ('GPA', models.FloatField()),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVprofileSubmission.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=50)),
                ('File', models.FileField(upload_to='documents/')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVprofileSubmission.submission')),
            ],
        ),
    ]
