# Generated by Django 3.0.8 on 2021-06-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CVprofileSubmission', '0002_auto_20210621_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetials',
            old_name='LastNmae',
            new_name='LastName',
        ),
        migrations.AddField(
            model_name='userdetials',
            name='dateOfBirth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CVprofileSubmission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
